# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/ullbergm/object-lease-controller
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "latest"

group: ""
version: ""
kind:
  singular: ""
  plural: ""

# These are used by the webhook configuration for the LeaseController CRD, not the helm chart itself.
webhook:
  enabled: false            # Enable validation for this GVK
  failurePolicy: Ignore     # "Fail" to reject invalid objects or "Ignore" to log but allow

leaderElection:
  enabled: true

metrics:
  enabled: true
  port: 8080
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels: {}
