apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: object-lease-webhook-rolebinding
  labels:
    app: object-lease-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: object-lease-webhook-role
subjects:
- kind: ServiceAccount
  name: object-lease-webhook
  namespace: system
