apiVersion: v1
kind: Service
metadata:
  name: object-lease-webhook-service
  namespace: system
  labels:
    app: object-lease-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: object-lease-webhook-cert
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    app: object-lease-webhook
  type: ClusterIP
