---
name: PR - Size Labeler

on:
  pull_request:
  workflow_dispatch:

jobs:
  size-label:
    name: Label Size
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@f8edde36b3be04b4f65dcfead05dc8691b374348" # v0.5.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "30": "M",
              "100": "L",
              "500": "XL",
              "1000": "XXL"
            }
